export type Product = {
  slug: string;
  name: string;
  shortName: string;
  image: string;
  price: number;
  oldPrice: number;
  rating: number;
  badge: string;
  audience: "men" | "women" | "professional" | "pet" | "utility";
  category: string;
  groups: string[];
  features: string[];
  description: string;
};

const shared = {
  description:
    "Professional-grade VGR grooming technology engineered for dependable performance, comfortable control and a precise finish at home or in the salon.",
};

export const products: Product[] = [
  {
    ...shared,
    slug: "rosso-professional-beard-moustache-trimmer",
    name: "VGR Rosso Professional Beard & Moustache Trimmer for Men (Red)",
    shortName: "Rosso Professional Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/zqodvesbryao3p9ded8p.webp?v=1761639395&width=1200",
    price: 1599,
    oldPrice: 2499,
    rating: 5,
    badge: "Limited Edition",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["new-arrival", "red-series", "hair-trimmer", "trimmer", "category-men", "vgr-personal-use-trimmer"],
    features: ["400 min runtime", "Type-C fast charging", "Titanium coated blades", "0.25–4.5 mm trim"],
  },
  {
    ...shared,
    slug: "vgr-v-071-hair-trimmer-for-men-silver",
    name: "VGR V-071 Hair Trimmer For Men, Silver",
    shortName: "V-071 Hair Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/1_-_2025-11-29T165614.742.jpg?v=1764417571&width=1200",
    price: 999,
    oldPrice: 1399,
    rating: 4.5,
    badge: "Bestseller",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["hair-trimmer", "trimmer", "category-men", "vgr-personal-use-trimmer", "under-1000-models", "product-under-1500"],
    features: ["5 speed control", "Digital display", "Cordless use", "Precision blade"],
  },
  {
    ...shared,
    slug: "vgr-v-937-hair-trimmer-for-men-black",
    name: "VGR V-937 Hair Trimmer For Men, Black",
    shortName: "V-937 Hair Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/Copy_of_01.jpg?v=1764418932&width=1200",
    price: 1399,
    oldPrice: 1799,
    rating: 4.5,
    badge: "Popular",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["hair-trimmer", "trimmer", "category-men", "vgr-personal-use-trimmer", "product-under-1500"],
    features: ["Long-life motor", "LED display", "Multiple guide combs", "Travel lock"],
  },
  {
    ...shared,
    slug: "vgr-v-290-hair-trimmer-for-men-gold",
    name: "VGR V-290 Hair Trimmer For Men",
    shortName: "V-290 Hair Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/13.webp?v=1760682705&width=1200",
    price: 1299,
    oldPrice: 1599,
    rating: 4.7,
    badge: "Icon",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["hair-trimmer", "trimmer", "category-men", "vgr-personal-use-trimmer", "product-under-1500"],
    features: ["Gold finish", "Digital runtime display", "Low-noise motor", "USB charging"],
  },
  {
    ...shared,
    slug: "vgr-v-228-hair-trimmer-for-men",
    name: "VGR V-228 Hair Trimmer For Men",
    shortName: "V-228 Hair Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/1_-_2025-11-29T172334.182.jpg?v=1764417667&width=1200",
    price: 1899,
    oldPrice: 2299,
    rating: 4.7,
    badge: "Pro choice",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["hair-trimmer", "trimmer", "category-men", "vgr-personal-use-trimmer", "product-under-2000"],
    features: ["Metal body", "T-blade", "Digital display", "Long runtime"],
  },
  {
    ...shared,
    slug: "vgr-v-055-hair-trimmer-for-men-black",
    name: "VGR V-055 Hair Trimmer For Men, Black",
    shortName: "V-055 Hair Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/1.1_34.jpg?v=1764417530&width=1200",
    price: 999,
    oldPrice: 1299,
    rating: 4.7,
    badge: "Value pick",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["hair-trimmer", "trimmer", "category-men", "vgr-budget-friendly-trimmer", "under-1000-models", "product-under-1500"],
    features: ["Compact design", "Cordless operation", "Guide combs", "USB charging"],
  },
  {
    ...shared,
    slug: "vgr-v-052-hair-trimmer-for-men-blue",
    name: "V-052 Blue Beard Trimmer for Men",
    shortName: "V-052 Beard Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/00_1_7d2cf10a-655d-44b8-8cb5-7bfa0589468f.webp?v=1744698786&width=1200",
    price: 979,
    oldPrice: 1199,
    rating: 4.5,
    badge: "Budget icon",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["hair-trimmer", "trimmer", "category-men", "vgr-budget-friendly-trimmer", "under-1000-models", "product-under-1500"],
    features: ["Blue finish", "Sharp T-blade", "Low noise", "Travel friendly"],
  },
  {
    ...shared,
    slug: "vgr-v-932-pocket-hair-trimmer-for-men-black",
    name: "VGR V-932 Pocket Hair Trimmer For Men (Black)",
    shortName: "V-932 Pocket Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/1_-_2025-11-29T175257.449.jpg?v=1764419027&width=1200",
    price: 1349,
    oldPrice: 1699,
    rating: 5,
    badge: "Pocket pro",
    audience: "men",
    category: "Hair Trimmer",
    groups: ["new-arrival", "hair-trimmer", "trimmer", "category-men", "product-under-1500"],
    features: ["Pocket-size body", "Close-cut blade", "USB-C charge", "Protective cap"],
  },
  {
    ...shared,
    slug: "vgr-mr-super-power-stepless-pro-4-in-1-barber",
    name: "VGR Mr. SUPER POWER Stepless Pro 4-in-1 Barber Series Combo Kit for Salon, Red",
    shortName: "Mr. Super Power 4-in-1",
    image: "https://vgrofficial.in/cdn/shop/files/1741669611469_VGR4in1-1_959b86c5-3385-41d7-afec-7a1b879c8d95.jpg?v=1764419085&width=1200",
    price: 32999,
    oldPrice: 50000,
    rating: 4.9,
    badge: "Super Power",
    audience: "professional",
    category: "Barber Series",
    groups: ["new-arrival", "red-series", "vgr-professional-use-tools", "clipper", "category-men"],
    features: ["4-in-1 system", "Stepless control", "Salon motor", "Premium case"],
  },
  {
    ...shared,
    slug: "vgr-v-001-professional-hair-clipper-for-men-green",
    name: "VGR V-001 Professional Hair Clipper For Men, Red",
    shortName: "V-001 Professional Clipper",
    image: "https://vgrofficial.in/cdn/shop/files/533af7b5-a57f-4726-b636-006a90caab6c.jpg?v=1764419222&width=1200",
    price: 4999,
    oldPrice: 6999,
    rating: 4.8,
    badge: "Salon",
    audience: "professional",
    category: "Hair Clipper",
    groups: ["new-arrival", "clipper", "vgr-professional-use-tools", "category-men"],
    features: ["Salon-grade motor", "Fade control", "Metal housing", "Cordless power"],
  },
  {
    ...shared,
    slug: "vgr-v-885-s2-rotafinity-pro-2-in-1-barber-set",
    name: "VGR V-885 S2 Rotafinity Pro 2 in 1 Barber Set",
    shortName: "Rotafinity Pro Barber Set",
    image: "https://vgrofficial.in/cdn/shop/files/V-885-S2-Gold.jpg?v=1760343453&width=1200",
    price: 8999,
    oldPrice: 11999,
    rating: 4.8,
    badge: "Professional",
    audience: "professional",
    category: "Barber Series",
    groups: ["new-arrival", "clipper", "vgr-professional-use-tools", "category-men"],
    features: ["Clipper + trimmer", "Vector motor", "Gold finish", "Charging dock"],
  },
  {
    ...shared,
    slug: "vgr-v-196-v-996-professional-barber-combo",
    name: "VGR V-196 & V-996 Professional Barber Combo",
    shortName: "Professional Barber Combo",
    image: "https://vgrofficial.in/cdn/shop/files/Untitled_design_47.webp?v=1760330066&width=1200",
    price: 6999,
    oldPrice: 8999,
    rating: 4.7,
    badge: "Combo",
    audience: "professional",
    category: "Barber Series",
    groups: ["clipper", "vgr-professional-use-tools", "category-men"],
    features: ["Two-tool system", "High-torque motors", "Precision blades", "Salon accessories"],
  },
  {
    ...shared,
    slug: "vgr-v-035t-professional-hair-trimmer-9000rpm",
    name: "VGR V-035T Professional Hair Trimmer with 9000 RPM Vector Motor",
    shortName: "V-035T Vector Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/VGR_official.jpg?v=1764069719&width=1200",
    price: 12499,
    oldPrice: 21499,
    rating: 4.9,
    badge: "9000 RPM",
    audience: "professional",
    category: "Hair Trimmer",
    groups: ["new-arrival", "hair-trimmer", "trimmer", "vgr-professional-use-tools", "category-men"],
    features: ["9000 RPM vector motor", "Zero-gap blade", "Wireless charging", "Pro runtime"],
  },
  {
    ...shared,
    slug: "vgr-v-583-automatic-hair-curler",
    name: "VGR V-583 Automatic Hair Curler For Women (Green)",
    shortName: "V-583 Automatic Curler",
    image: "https://vgrofficial.in/cdn/shop/files/freepik_change-the-face-expression-of-model_0001_4.png?v=1774473579&width=1200",
    price: 3799,
    oldPrice: 5199,
    rating: 4.5,
    badge: "Viral",
    audience: "women",
    category: "Hair Curler",
    groups: ["new-arrival", "womens-grooming-tools", "category-women", "hair-volumizer"],
    features: ["Automatic curl chamber", "Smart heat control", "Anti-tangle", "Cordless styling"],
  },
  {
    ...shared,
    slug: "vgr-v-706-epilator-for-women-white",
    name: "VGR V-706 Professional Women’s Epilator, Smooth Skin Care",
    shortName: "V-706 Women’s Epilator",
    image: "https://cdn.shopify.com/s/files/1/0710/2716/3427/files/Person_usingVGR_V-706.webp?v=1764069563",
    price: 999,
    oldPrice: 1699,
    rating: 4.5,
    badge: "Smooth care",
    audience: "women",
    category: "Epilator",
    groups: ["womens-grooming-tools", "category-women", "under-1000-models", "product-under-1500"],
    features: ["Gentle epilation", "LED guide", "Multiple heads", "Easy cleaning"],
  },
  {
    ...shared,
    slug: "vgr-epilator-for-women",
    name: "VGR V-722 Professional 2 in 1 Cordless Epilator for Women",
    shortName: "V-722 Cordless Epilator",
    image: "https://cdn.shopify.com/s/files/1/0710/2716/3427/files/WhatsApp_Image_2024-09-28_at_12.54.32_PM.webp?v=1741077204",
    price: 2499,
    oldPrice: 2999,
    rating: 4.6,
    badge: "2 in 1",
    audience: "women",
    category: "Epilator",
    groups: ["womens-grooming-tools", "category-women", "product-under-2500"],
    features: ["Cordless care", "Two heads", "Skin-friendly design", "Travel pouch"],
  },
  {
    ...shared,
    slug: "vgr-v-597-hair-curling-iron-for-women",
    name: "VGR V-597 5 Barrel Hair Curler For Women, Green",
    shortName: "V-597 5 Barrel Curler",
    image: "https://vgrofficial.in/cdn/shop/files/AnyConv.com__new1_79b4f13b-098b-4c18-a252-911621100be4_1.webp?v=1741072099&width=1200",
    price: 2499,
    oldPrice: 2999,
    rating: 4.4,
    badge: "5 barrel",
    audience: "women",
    category: "Hair Curler",
    groups: ["womens-grooming-tools", "category-women", "hair-volumizer", "product-under-2500"],
    features: ["Five ceramic barrels", "Fast heating", "Wave styling", "Heat-safe grip"],
  },
  {
    ...shared,
    slug: "vgr-v-511-hair-straightener-for-women-white",
    name: "VGR V-511 Hair Straightener For Women, White",
    shortName: "V-511 Hair Straightener",
    image: "https://vgrofficial.in/cdn/shop/files/511.1.webp?v=1741061727&width=1200",
    price: 2249,
    oldPrice: 2699,
    rating: 4.5,
    badge: "Sleek finish",
    audience: "women",
    category: "Hair Straightener",
    groups: ["womens-grooming-tools", "category-women", "hair-straightener", "product-under-2500"],
    features: ["Ceramic plates", "Adjustable temperature", "Fast heat-up", "360° cord"],
  },
  {
    ...shared,
    slug: "vgr-v-492-hot-air-brush-black",
    name: "VGR V-492 Professional Hot Air Brush for Women (1000W, Black)",
    shortName: "V-492 Hot Air Brush",
    image: "https://vgrofficial.in/cdn/shop/files/VGR_V-492_Hot_Air_Brush.webp?v=1764066945&width=1200",
    price: 2299,
    oldPrice: 2999,
    rating: 4.3,
    badge: "Volume",
    audience: "women",
    category: "Hair Volumizer",
    groups: ["womens-grooming-tools", "category-women", "hair-volumizer", "product-under-2500"],
    features: ["1000W airflow", "Volume brush", "Ionic care", "Two heat modes"],
  },
  {
    ...shared,
    slug: "vgr-v-439-foldable-hair-dryer-black",
    name: "VGR V-439 Foldable Hair Dryer For Unisex, Black",
    shortName: "V-439 Foldable Dryer",
    image: "https://vgrofficial.in/cdn/shop/files/1.1_f44fa006-2edf-4d52-951b-aae983808a85.webp?v=1750416453&width=1200",
    price: 1499,
    oldPrice: 1999,
    rating: 4.2,
    badge: "Travel",
    audience: "women",
    category: "Hair Dryer",
    groups: ["womens-grooming-tools", "category-women", "hair-dryer", "hair-dryer-1", "product-under-1500"],
    features: ["Foldable handle", "Dual speed", "Concentrator nozzle", "Travel ready"],
  },
  {
    ...shared,
    slug: "vgr-v-569-4-in-1-hair-beauty-styler-green",
    name: "VGR V-569 Professional 4 In 1 Hair Beauty Styler",
    shortName: "V-569 4-in-1 Styler",
    image: "https://vgrofficial.in/cdn/shop/files/1_2.webp?v=1741070242&width=1200",
    price: 1849,
    oldPrice: 2499,
    rating: 4.4,
    badge: "4 in 1",
    audience: "women",
    category: "Hair Volumizer",
    groups: ["womens-grooming-tools", "category-women", "hair-volumizer", "hair-straightener", "product-under-2000"],
    features: ["Straighten", "Curl", "Crimp", "Wave"],
  },
  {
    ...shared,
    slug: "vgr-v-640hd-professional-hair-dryer-barber-series",
    name: "VGR V-640HD Professional Hair Dryer | Barber Series",
    shortName: "V-640HD Pro Hair Dryer",
    image: "https://vgrofficial.in/cdn/shop/files/V-640_VGR_V-640HD_Professional_Hair_Dryer_Barber_Series_1600_1900W_High-Speed_BLDC_Motor.jpg?v=1764073685&width=1200",
    price: 7499,
    oldPrice: 13499,
    rating: 4.8,
    badge: "Barber Series",
    audience: "professional",
    category: "Hair Dryer",
    groups: ["new-arrival", "hair-dryer", "hair-dryer-1", "vgr-professional-use-tools"],
    features: ["1600–1900W", "High-speed BLDC motor", "Ion+ care", "Salon nozzles"],
  },
  {
    ...shared,
    slug: "vgr-v-421-hair-dryer-unisex-green",
    name: "VGR V-421 Hair Dryer For Unisex, Green",
    shortName: "V-421 Hair Dryer",
    image: "https://vgrofficial.in/cdn/shop/files/00_5.webp?v=1740998949&width=1200",
    price: 1299,
    oldPrice: 1799,
    rating: 4.8,
    badge: "Everyday",
    audience: "women",
    category: "Hair Dryer",
    groups: ["hair-dryer", "hair-dryer-1", "category-women", "product-under-1500"],
    features: ["Foldable handle", "Dual speed", "Cool shot", "Lightweight"],
  },
  {
    ...shared,
    slug: "vgr-v-445-professional-bldc-hair-dryer",
    name: "VGR V-445 Professional BLDC Hair Dryer",
    shortName: "V-445 BLDC Dryer",
    image: "https://cdn.shopify.com/s/files/1/0710/2716/3427/files/1_7afeefd7-5568-4d56-86b4-91f0feb53f27.jpg?v=1764838443",
    price: 5999,
    oldPrice: 8999,
    rating: 4.8,
    badge: "BLDC",
    audience: "professional",
    category: "Hair Dryer",
    groups: ["new-arrival", "hair-dryer", "hair-dryer-1", "vgr-professional-use-tools"],
    features: ["BLDC motor", "Fast airflow", "Ionic technology", "Memory mode"],
  },
  {
    ...shared,
    slug: "vgr-v-469-professional-hair-dryer",
    name: "VGR V-469 Professional BLDC Hair Dryer",
    shortName: "V-469 BLDC Dryer",
    image: "https://vgrofficial.in/cdn/shop/files/V-469-Black_bc3121e6-2515-43f2-8bdc-20d5c168a388.webp?v=1760331654&width=1200",
    price: 6499,
    oldPrice: 9499,
    rating: 4.8,
    badge: "Pro airflow",
    audience: "professional",
    category: "Hair Dryer",
    groups: ["hair-dryer", "hair-dryer-1", "vgr-professional-use-tools"],
    features: ["High-speed BLDC", "Magnetic nozzle", "Low-noise design", "Ion care"],
  },
  {
    ...shared,
    slug: "vgr-v-240-professional-pet-trimmer",
    name: "VGR V-240 Professional Pet Trimmer",
    shortName: "V-240 Pet Trimmer",
    image: "https://vgrofficial.in/cdn/shop/files/1.1_eb7ef5e6-b556-4189-b080-859056673e74.webp?v=1761392756&width=1200",
    price: 1699,
    oldPrice: 2299,
    rating: 4.6,
    badge: "Pet care",
    audience: "pet",
    category: "Pet Trimmer",
    groups: ["pet", "pet-grooming-tools", "product-under-2000"],
    features: ["Low-noise motor", "Pet-safe blade", "Guide combs", "Cordless grooming"],
  },
  {
    ...shared,
    slug: "vgr-v-208-professional-pet-hair-clipper",
    name: "VGR V-208 Professional Pet Clipper for Dogs, Cats & All Animals",
    shortName: "V-208 Pet Clipper",
    image: "https://cdn.shopify.com/s/files/1/0710/2716/3427/files/1.1_10.webp?v=1741413726",
    price: 2499,
    oldPrice: 3299,
    rating: 4.7,
    badge: "All breeds",
    audience: "pet",
    category: "Pet Clipper",
    groups: ["pet", "pet-grooming-tools", "product-under-2500"],
    features: ["180 min runtime", "Digital display", "Low vibration", "Multiple combs"],
  },
  {
    ...shared,
    slug: "vgr-v-219-professional-pet-trimmer",
    name: "VGR V-219 Professional Pet Trimmer",
    shortName: "V-219 Pet Trimmer",
    image: "https://cdn.shopify.com/s/files/1/0710/2716/3427/files/1_2_969b5764-4468-429b-b224-daf0af6d673a.webp?v=1761391612",
    price: 1999,
    oldPrice: 2699,
    rating: 4.6,
    badge: "Quiet care",
    audience: "pet",
    category: "Pet Trimmer",
    groups: ["pet", "pet-grooming-tools", "product-under-2000"],
    features: ["Quiet grooming", "Fine adjustment", "Cordless use", "Washable head"],
  },
  {
    ...shared,
    slug: "vgr-v-206-professional-pet-clipper",
    name: "VGR V-206 Professional Pet Clipper Heavy-Duty Grooming Kit",
    shortName: "V-206 Pet Grooming Kit",
    image: "https://vgrofficial.in/cdn/shop/files/51UZUY0-d5L._SX679.jpg?v=1744891654&width=1200",
    price: 4499,
    oldPrice: 5999,
    rating: 4.8,
    badge: "Heavy duty",
    audience: "pet",
    category: "Pet Clipper",
    groups: ["pet", "pet-grooming-tools"],
    features: ["Heavy-duty clipper", "8 guide combs", "Scissors included", "Metal pin brush"],
  },
  {
    ...shared,
    slug: "vgr-v-818-professional-lint-remover-lint-roller-green",
    name: "VGR V-818 Professional Lint Remover Lint Roller (Green)",
    shortName: "V-818 Lint Remover",
    image: "https://vgrofficial.in/cdn/shop/files/1.1.png?v=1740124210&width=1200",
    price: 1199,
    oldPrice: 1599,
    rating: 4.5,
    badge: "Home care",
    audience: "utility",
    category: "Lint Remover",
    groups: ["new-arrival", "lint-remover", "product-under-1500"],
    features: ["Fabric-safe blades", "Rechargeable", "Easy-clean chamber", "Protective cap"],
  },
  {
    ...shared,
    slug: "portable-professional-lint-remover",
    name: "VGR V-810 Professional Rechargeable Lint Remover, Blue",
    shortName: "V-810 Lint Remover",
    image: "https://vgrofficial.in/cdn/shop/files/1.1_16.webp?v=1741080185&width=1200",
    price: 1299,
    oldPrice: 1699,
    rating: 4.4,
    badge: "Rechargeable",
    audience: "utility",
    category: "Lint Remover",
    groups: ["lint-remover", "product-under-1500"],
    features: ["Large shaving head", "Rechargeable battery", "Comfort grip", "Lint chamber"],
  },
  {
    ...shared,
    slug: "rechargeable-lint-remover-professional-blue",
    name: "VGR V-813 Professional Rechargeable Lint Remover",
    shortName: "V-813 Lint Remover",
    image: "https://cdn.shopify.com/s/files/1/0710/2716/3427/files/1.1_21.webp?v=1741080984",
    price: 1399,
    oldPrice: 1899,
    rating: 4.5,
    badge: "Fabric care",
    audience: "utility",
    category: "Lint Remover",
    groups: ["lint-remover", "product-under-1500"],
    features: ["Three speed modes", "LED display", "USB charging", "Safety lock"],
  },
  {
    ...shared,
    slug: "vgr-v-811-professional-2-in-1-lint-remover",
    name: "VGR V-811 Professional 2-in-1 Lint Remover (Green)",
    shortName: "V-811 2-in-1 Lint Remover",
    image: "https://vgrofficial.in/cdn/shop/files/1Image_1.webp?v=1741080343&width=1200",
    price: 1599,
    oldPrice: 2199,
    rating: 4.6,
    badge: "2 in 1",
    audience: "utility",
    category: "Lint Remover",
    groups: ["lint-remover", "product-under-2000"],
    features: ["Fabric shaver", "Lint roller", "Rechargeable", "Easy maintenance"],
  },
];

export const collectionMeta: Record<string, { title: string; eyebrow: string; description: string }> = {
  "new-arrival": { title: "New Arrivals", eyebrow: "Just landed", description: "The newest VGR grooming innovations, ready to define your next signature." },
  "category-men": { title: "Men’s Grooming", eyebrow: "For him", description: "Trimmers, clippers and barber-grade tools built for precision and control." },
  "category-women": { title: "Women’s Grooming", eyebrow: "For her", description: "High-performance styling, hair care and personal grooming tools." },
  "womens-grooming-tools": { title: "Women’s Grooming", eyebrow: "Shape. Style. Shine.", description: "Curl, smooth, dry and define with tools designed around every expression." },
  "vgr-professional-use-tools": { title: "Professional Tools", eyebrow: "Salon series", description: "High-speed motors, precise blades and durable systems made for professionals." },
  "hair-trimmer": { title: "Hair Trimmers", eyebrow: "Precision edit", description: "Close detailing, clean lines and reliable cordless performance." },
  trimmer: { title: "VGR Trimmers", eyebrow: "Precision edit", description: "A complete selection of personal and professional trimmers." },
  clipper: { title: "Hair Clippers", eyebrow: "Power edit", description: "Performance clippers for fades, bulk removal and everyday cutting." },
  "hair-volumizer": { title: "Hair Volumizers", eyebrow: "Volume edit", description: "Hot-air brushes and multi-stylers for effortless volume and shape." },
  "hair-straightener": { title: "Hair Straighteners", eyebrow: "Smooth edit", description: "Fast-heating styling tools for a sleek, controlled finish." },
  "hair-dryer": { title: "Hair Dryers", eyebrow: "Air performance", description: "From travel-ready dryers to high-speed professional BLDC systems." },
  "hair-dryer-1": { title: "Hair Dryers", eyebrow: "Air performance", description: "From travel-ready dryers to high-speed professional BLDC systems." },
  "lint-remover": { title: "Lint Removers", eyebrow: "Fabric care", description: "Rechargeable fabric-care tools that keep everyday essentials looking new." },
  pet: { title: "Pet Grooming", eyebrow: "Quiet care", description: "Low-noise, pet-safe clippers and complete grooming kits." },
  "pet-grooming-tools": { title: "Pet Grooming", eyebrow: "Quiet care", description: "Low-noise, pet-safe clippers and complete grooming kits." },
  "red-series": { title: "Limited Red Series", eyebrow: "VGR icons", description: "Statement tools with professional power and a signature red finish." },
  "vgr-personal-use-trimmer": { title: "Personal-Use Trimmers", eyebrow: "Everyday precision", description: "Easy-to-use grooming tools for a sharp finish at home." },
  "vgr-budget-friendly-trimmer": { title: "Budget-Friendly Trimmers", eyebrow: "Smart value", description: "Dependable VGR performance at accessible prices." },
  "product-under-800": { title: "Products Under ₹800", eyebrow: "Shop by budget", description: "Useful grooming essentials at an easy everyday price." },
  "under-1000-models": { title: "Products Under ₹1,000", eyebrow: "Shop by budget", description: "VGR favourites priced below ₹1,000." },
  "product-under-1500": { title: "Products Under ₹1,500", eyebrow: "Shop by budget", description: "A strong edit of bestselling grooming and personal-care tools." },
  "product-under-2000": { title: "Products Under ₹2,000", eyebrow: "Shop by budget", description: "More performance, more choice, still under ₹2,000." },
  "product-under-2500": { title: "Products Under ₹2,500", eyebrow: "Shop by budget", description: "Feature-rich VGR tools curated under ₹2,500." },
  all: { title: "All Products", eyebrow: "The complete edit", description: "Explore the full world of VGR grooming and personal care." },
  collections: { title: "All Products", eyebrow: "The complete edit", description: "Explore the full world of VGR grooming and personal care." },
};

export const formatPrice = (value: number) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

export const productBySlug = (slug: string) =>
  products.find((product) => product.slug === slug || (slug === "automatic-hair-curler" && product.slug === "vgr-v-583-automatic-hair-curler"));

export const productsForCollection = (slug: string) => {
  if (slug === "all" || slug === "collections") return products;
  if (slug === "shaver") return products.filter((product) => product.audience === "men");
  if (slug === "product-under-800") return products.filter((product) => product.price < 800);
  if (slug === "under-1000-models") return products.filter((product) => product.price <= 1000);
  if (slug === "product-under-1500") return products.filter((product) => product.price <= 1500);
  if (slug === "product-under-2000") return products.filter((product) => product.price <= 2000);
  if (slug === "product-under-2500") return products.filter((product) => product.price <= 2500);
  return products.filter((product) => product.groups.includes(slug));
};
